# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'страница FAQ', 'verbose_name_plural': 'страницы FAQ'},
        ),
    ]
