# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='latitude',
            field=models.FloatField(default=50.451435, help_text='Используется в картах Google', verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='longitude',
            field=models.FloatField(default=30.511989, help_text='Используется в картах Google', verbose_name='Долгота'),
        ),
    ]
