# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 16:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.wagtailcore.fields.StreamField((('carousel_element', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Картинка для карусели (минимум 1920х900)', label='Картинка')), ('headline', wagtail.wagtailcore.blocks.CharBlock(help_text='Заголовок картинки карусели', label='Заголовок', max_length=50)), ('caption', wagtail.wagtailcore.blocks.CharBlock(help_text='Подпись к заголовку', label='Подпись', max_length=50)), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='Ссылка (опционально)', label='Ссылка', required=False))))),), blank=True),
        ),
    ]
