# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 18:01
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180221_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='diseases',
            field=wagtail.wagtailcore.fields.StreamField((('болезни', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(label='Заголовок секции')), ('text', wagtail.wagtailcore.blocks.TextBlock(label='Текст')), ('diseases', wagtail.wagtailcore.blocks.ListBlock(home.blocks._SingleDiseaseBlock, label='Список заболеваний'))))),), blank=True, verbose_name='Список заболеваний'),
        ),
    ]
