# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 23:10
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180223_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us',
            field=wagtail.wagtailcore.fields.StreamField((('why_choose_us', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(label='Заголовок секции')), ('text', wagtail.wagtailcore.blocks.TextBlock(label='Текст')), ('diseases', wagtail.wagtailcore.blocks.ListBlock(home.blocks._WhyChoseUsBlock, label='Список карточек', max_num=4))))),), blank=True, verbose_name='Почему выбрать нас'),
        ),
    ]
