# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 23:12
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180224_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='selected_methods',
            field=wagtail.wagtailcore.fields.StreamField((('selected_methods', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(label='Заголовок секции')), ('text', wagtail.wagtailcore.blocks.TextBlock(label='Текст')), ('selected_methods', wagtail.wagtailcore.blocks.ListBlock(home.blocks._MethodBlock, label='Методики', max_num=3, min_num=3))))),), blank=True, verbose_name='Выбраные методики'),
        ),
    ]
