# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 13:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_selected_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_us',
            field=wagtail.wagtailcore.fields.StreamField((('contact_us', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(blank=True, help_text='Картинка слева от надписи (желательно твое фото)', label='Картинка')), ('text', wagtail.wagtailcore.blocks.CharBlock(default='Задать вопрос или записаться на сеанс', help_text='Основной текстовый блок по центру', label='Текст', max_length=40)), ('button_text', wagtail.wagtailcore.blocks.CharBlock(default='Связаться с нами', help_text='Текст на кнопке', label='Кнопка', max_length=25))))),), blank=True, verbose_name='Блок "Свяжитесь с нами"'),
        ),
    ]
