# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodindexpage',
            options={'verbose_name': 'Методики (список)', 'verbose_name_plural': 'Методики (список)'},
        ),
        migrations.AlterModelOptions(
            name='methodpage',
            options={'verbose_name': 'Методика', 'verbose_name_plural': 'Методика'},
        ),
    ]
