# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 23:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0003_methodpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('content', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock(help_text='Введите заголовок текстового блока')), ('text', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', help_text='Введите текст блока'))))),), blank=True, verbose_name='Основной текстовый блок'),
        ),
    ]
