# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSpecialistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('main_info', models.TextField(blank=True)),
                ('body', wagtail.wagtailcore.fields.StreamField((('content', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.CharBlock(help_text='Введите заголовок текстового блока')), ('text', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', help_text='Введите текст блока'))))),), blank=True, verbose_name='Основной текстовый блок')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='картинка')),
            ],
            options={
                'verbose_name_plural': 'О специалисте',
                'verbose_name': 'О специалисте',
            },
            bases=('wagtailcore.page',),
        ),
    ]
