# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_specialist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutspecialistpage',
            name='main_info',
            field=models.TextField(blank=True, verbose_name='Основная краткая информация'),
        ),
    ]
