# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_specialist', '0002_auto_20180212_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutspecialistpage',
            name='profession',
            field=models.CharField(blank=True, max_length=250, verbose_name='Специальность'),
        ),
    ]
